[package]
name = "charengine"
version = "0.1.0"
edition = "2018"
authors=["Callum Mackenzie Alexxander1611@gmail.com"]
license="MIT"

[dependencies]
charmath = { path = "./charmath" }
charrender = { path = "./charrender" }
