[package]
name="charmath"
version="0.1.2"
edition="2018"
authors=["Callum Mackenzie Alexxander1611@gmail.com"]
license="MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen="0.2"
