[package]
name = "charrender"
version = "0.1.0"
edition = "2021"
authors=["Callum Mackenzie Alexxander1611@gmail.com"]
license="MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen="0.2"
